# Environments in a latex file that we will skip
IGNORED_ENVS = ["lstlisting",
                "comment",
                "math",
                "displaymath",
                "equation",
                "aligned",
                "theorem",
                "figure",
                "figure*",
                "tikzpicture",
                "table",
                "table*",
                "restattable",
                "align",
                "math*",
                "displaymath*",
                "equation*",
                "aligned*",
                "align*",
                "lrbox",
                "cblock"]
